### PR TITLE
Listen to region-update-end

### PR DESCRIPTION
**Pull request by evenbrenna**
Looks to me like the bug where lowering the tempo shortens the loop [ch869] is not (or at least not only) a math issue. 

I have a feeling that the waveform UI and input fields are causing some sort of update loop where one is updated, the other is updated to reflect the change which causes the first one to update itself again etc.

This change makes things a lot better as far as I can tell. For example, I can type in e.g. `12` in the loop length input and change the tempo without having the loop length changed. 

However, I can now type in a loop length below the minimum requirement (e.g. 1). When I do, the audio plays a one beat loop, but the marked loop in the waveform never goes below 3 beats.

Not sure if I have caused a new issue or if there are more things to fix...

### CODE REVIEW

**Comment by kimroen** [comment]
> I have a feeling that the waveform UI and input fields are causing some sort of update loop where one is updated, the other is updated to reflect the change which causes the first one to update itself again etc.

Yeah, passing in new values to the component does trigger the region updated callback, updating inputs again. But once the update results in the same values as the inputs already have, the feedback loop stops.

I changed this event on purpose, because without this change the input fields don’t update while you are dragging the region, and I enjoy that behavior more than the one where it waits until you have let go of the region.

**Comment by kimroen** [comment]
> However, I can now type in a loop length below the minimum requirement (e.g. 1). When I do, the audio plays a one beat loop, but the marked loop in the waveform never goes below 3 beats.

Yeah, this is because the minimum and maximum values are enforced when wavesurfer is rendering the region, but the updated values aren’t saved to the region itself. This is why I’m also doing this calculation in the event handler. Now with the change in event, updating the region from outside the component doesn’t trigger this logic.

I’ll need to do something about the way this works to fix the other things too though, so maybe it’ll just get fixed as a byproduct of that. Thanks for looking at it though, I appreciate it!

**Comment by kimroen** [comment]
Hey, that’s amazing!! Can you explain why? 😅😅

**Comment by evenbrenna** [comment]
> Hey, that’s amazing!! Can you explain why that works? 😅😅

Not really. My theory was that some floating point nonsense might be causing us to floor x.999999 and trigger the update loop again. No idea if that’s the case though.

**Comment by kimroen** [comment]
Fixes [`[ch874]` Weird behavior after changing bpm](https://app.clubhouse.io/voisey/story/874/weird-behavior-after-changing-bpm)

**Pull request merged**
